language: cpp
sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-4.9
            - cmake-data
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - cmake-data
            - cmake
      env:
         - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-6
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-7
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # clang
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
            - george-edison55-precise-backports
          packages:
            - clang-3.8
            - cmake-data
            - cmake
      env:
        - MATRIX_EVAL="CC=clang-3.8 && CXX=clang++-3.8"
    # OSX
    - os: osx
      osx_image: xcode8
      env:
        - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
before_install:
    - eval "${MATRIX_EVAL}"
compiler:
  - gcc
install:
  - pip install --user conan
  - conan user
  - conan remote add slidewave https://api.bintray.com/conan/slidewavellc/conan-libs
  - conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
script:
  - conan install . -s build_type=Release --build=missing
  - cmake . -DCMAKE_BUILD_TYPE=Release 
  - cmake --build . --config Release

