version: 1.0.{build}
image:
  - Visual Studio 2017
platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan --upgrade
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add slidewave https://api.bintray.com/conan/slidewavellc/conan-libs

build_script:
  - cmd: mkdir build
  - cmd: conan install -s build_type=Release -s arch=x86_64 -s compiler.runtime=MT --build=missing
  - cmd: cd build
  - cmd: cmake ../ -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config Release

 #test_script:
 #  - cmd: cd bin
 #  - cmd: encryption_test.exe

artifacts:
  - path: 'build\bin\aperture.exe'
    name: "Aperture"
    type: auto
  - path: 'build\bin\aperture.pdb'
    name: "Aperture Symbols"
    type: auto
