version: 1.0.{build}

image:
- Visual Studio 2017
- Ubuntu

platform:
- x64

skip_commits:
  files:
  - doc/*
  - README.md
  - .gitignore
  - LICENSE

cache:
- envs -> .appveyor.yml # Conan installation
- c:\conanData -> conanfile.txt
- /tmp/conanData -> conanfile.txt
- conanbuildinfo.cmake -> conanfile.txt
- conanbuildinfo.txt -> conanfile.txt
- conaninfo.txt -> conanfile.txt
- build -> CMakeLists.txt

install:
- echo "Downloading conan..."
- cmd: SET CONAN_USER_HOME=c:\conanData
- sh: export CONAN_USER_HOME=/tmp/conanData
- cmd: set PATH=%PATH%;%PYTHON%/Scripts/
- cmd: pip.exe install conan --upgrade
- sh: sudo -H pip install conan --upgrade
- conan user # Create the conan data directory
- conan --version
- conan remote add --force bincrafters https://api.bintray.com/conan/bincrafters/public-conan

before_build:
- ps: |
    if ($isLinux) {
      $env:EDITION = "linux"
    } else {
      $env:EDITION = "windows"
    }

build_script:
- ps: New-Item -Name build -ErrorAction SilentlyContinue
- cmd: conan install . -s build_type=Release -s arch=x86_64 -s compiler.runtime=MT --build=missing
- sh: conan install . -s build_type=Release -s arch=x86_64 --build=missing
- cmd: cd build
- sh: cd build
- cmd: cmake ..\ -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64"
- sh: cmake ../ -DCMAKE_BUILD_TYPE=Release
- cmake --build . --config Release


 #test_script:
 #  - cmd: cd bin
 #  - cmd: encryption_test.exe

artifacts:
  - path: 'build\bin\aperture.exe'
    name: Aperture-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(EDITION)
    type: auto

deploy:
  provider: GitHub
  auth_token:
    secure: DlRS0U90AATbPkzxigCLwaGe1vguHFeC3a0YhMZRA/OYEbLQ8+ybp2OGfqgwpbW4
  artifact: Aperture-$(APPVEYOR_BUILD_VERSION)-$(APPVEYOR_REPO_BRANCH)-$(EDITION)
  draft: true
  prerelease: false
  on:
    APPVEYOR_REPO_TAG: true
