version: 1.0.{build}
image:
  - Visual Studio 2017
platform:
  - x64

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan --upgrade
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version
  - cmd: conan remote add slidewave https://api.bintray.com/conan/slidewavellc/conan-libs
  - cmd: conan remote add conan-community https://api.bintray.com/conan/conan-community/conan

build_script:
  - cmd: mkdir build
  - cmd: conan install -s build_type=Release -s arch=x86_64 --build=missing
  - cmd: cd build
  - cmd: cmake ../ -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 15 2017 Win64"
  - cmd: cmake --build . --config Release

 #test_script:
 #  - cmd: cd bin
 #  - cmd: encryption_test.exe